# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "robson fagundes"
description: > # this means to ignore newlines until "email:"
   Junior Software Engineer 

email: robsonfagundes@gmail.com
#blog logo
logo: "/assets/images/me.png"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Robson Fagundes'
author: 'Robson Fagundes'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://robsonfagundes.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@robsonafagundes'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/robsonafagundes
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/RobsonAdaoFagundes
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/robsonfagundes
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
